algoritmo "Aumento Salarial"
// Função : Dar um aumento de 30% ao salário informado (Curso da Pacetech)
// Autor : Gabriel Sofiati Rausch
// Data : 01/11/2022
// Seção de Declarações 
var
salarioInformado, salarioAumentado: real
inicio
// Seção de Comandos
Escreval("Qual o seu salário atual?")
leia(salarioInformado)
salarioAumentado <- salarioInformado * (130 / 100)
Escreval("O salário com aumento será de:", salarioAumentado)

fimalgoritmo
