/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CalculadoraComInterface;

import java.text.DecimalFormat;

/**
 *
 * @author Windows
 */
public class Calculadora extends javax.swing.JFrame {

    double primeiroNumero;
    double segundoNumero;
    double result = 0;
    double sinal = 1;
    double mem = 0;
    boolean igual = false;
    boolean oper = false;
    boolean primeira = false;
    boolean i = false;
    boolean burroMode;
    String operacao;
    DecimalFormat deci = new DecimalFormat("0.00");

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBurroMode = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        visor = new javax.swing.JTextField();
        displayCalculadora = new javax.swing.JTextField();
        btPi = new javax.swing.JButton();
        btLog = new javax.swing.JButton();
        btLn = new javax.swing.JButton();
        btE = new javax.swing.JButton();
        btCos = new javax.swing.JButton();
        btCosh = new javax.swing.JButton();
        btRaiz = new javax.swing.JButton();
        btElevado = new javax.swing.JButton();
        btResto = new javax.swing.JButton();
        btFatorial = new javax.swing.JButton();
        btSen = new javax.swing.JButton();
        btSenh = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btDividir = new javax.swing.JButton();
        btVezes = new javax.swing.JButton();
        btMenos = new javax.swing.JButton();
        btTan = new javax.swing.JButton();
        btTanh = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btMais = new javax.swing.JButton();
        btMaisOuMenos = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        btRandom = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btDecimal = new javax.swing.JButton();
        btMemMais = new javax.swing.JButton();
        btMemMenos = new javax.swing.JButton();
        btMemoria = new javax.swing.JButton();
        btMemSet = new javax.swing.JButton();
        btMemClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        btBurroMode.setBackground(new java.awt.Color(0, 0, 0));
        btBurroMode.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btBurroMode.setForeground(new java.awt.Color(255, 255, 255));
        btBurroMode.setBorderPainted(false);
        btBurroMode.setContentAreaFilled(false);
        btBurroMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBurroMode.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btBurroMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBurroModeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        visor.setBackground(new java.awt.Color(51, 0, 0));
        visor.setFont(new java.awt.Font("Segoe UI", 1, 47)); // NOI18N
        visor.setForeground(new java.awt.Color(255, 255, 255));
        visor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visor.setText("Olá!");
        visor.setFocusable(false);
        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });

        displayCalculadora.setBackground(new java.awt.Color(51, 51, 51));
        displayCalculadora.setFont(new java.awt.Font("Segoe UI", 1, 47)); // NOI18N
        displayCalculadora.setForeground(new java.awt.Color(255, 255, 255));
        displayCalculadora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        displayCalculadora.setFocusable(false);

        btPi.setBackground(new java.awt.Color(102, 0, 153));
        btPi.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btPi.setForeground(new java.awt.Color(255, 255, 255));
        btPi.setText("π");
        btPi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPi.setName(""); // NOI18N
        btPi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPiActionPerformed(evt);
            }
        });

        btLog.setBackground(new java.awt.Color(102, 0, 153));
        btLog.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btLog.setForeground(new java.awt.Color(255, 255, 255));
        btLog.setText("log");
        btLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogActionPerformed(evt);
            }
        });

        btLn.setBackground(new java.awt.Color(102, 0, 153));
        btLn.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btLn.setForeground(new java.awt.Color(255, 255, 255));
        btLn.setText("ln");
        btLn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLnActionPerformed(evt);
            }
        });

        btE.setBackground(new java.awt.Color(102, 0, 153));
        btE.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btE.setForeground(new java.awt.Color(255, 255, 255));
        btE.setText("e");
        btE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEActionPerformed(evt);
            }
        });

        btCos.setBackground(new java.awt.Color(51, 153, 0));
        btCos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btCos.setForeground(new java.awt.Color(255, 255, 255));
        btCos.setText("cos");
        btCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCosActionPerformed(evt);
            }
        });

        btCosh.setBackground(new java.awt.Color(51, 153, 0));
        btCosh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btCosh.setForeground(new java.awt.Color(255, 255, 255));
        btCosh.setText("cosh");
        btCosh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCoshActionPerformed(evt);
            }
        });

        btRaiz.setBackground(new java.awt.Color(255, 51, 204));
        btRaiz.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btRaiz.setForeground(new java.awt.Color(255, 255, 255));
        btRaiz.setText("ⁿ√x");
        btRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRaizActionPerformed(evt);
            }
        });

        btElevado.setBackground(new java.awt.Color(255, 51, 204));
        btElevado.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btElevado.setForeground(new java.awt.Color(255, 255, 255));
        btElevado.setText("x^y");
        btElevado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btElevado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btElevado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElevadoActionPerformed(evt);
            }
        });

        btResto.setBackground(new java.awt.Color(255, 51, 204));
        btResto.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btResto.setForeground(new java.awt.Color(255, 255, 255));
        btResto.setText("%");
        btResto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestoActionPerformed(evt);
            }
        });

        btFatorial.setBackground(new java.awt.Color(255, 51, 204));
        btFatorial.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btFatorial.setForeground(new java.awt.Color(255, 255, 255));
        btFatorial.setText("!");
        btFatorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFatorial.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btFatorial.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btFatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFatorialActionPerformed(evt);
            }
        });

        btSen.setBackground(new java.awt.Color(51, 153, 0));
        btSen.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btSen.setForeground(new java.awt.Color(255, 255, 255));
        btSen.setText("sen");
        btSen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSenActionPerformed(evt);
            }
        });

        btSenh.setBackground(new java.awt.Color(51, 153, 0));
        btSenh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btSenh.setForeground(new java.awt.Color(255, 255, 255));
        btSenh.setText("senh");
        btSenh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSenhActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(204, 0, 0));
        btReset.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btReset.setForeground(new java.awt.Color(255, 255, 255));
        btReset.setText("C");
        btReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btReset.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        btReset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btResetKeyTyped(evt);
            }
        });

        btDividir.setBackground(new java.awt.Color(204, 102, 0));
        btDividir.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btDividir.setForeground(new java.awt.Color(255, 255, 255));
        btDividir.setText("÷");
        btDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDividir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btDividir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDividirActionPerformed(evt);
            }
        });

        btVezes.setBackground(new java.awt.Color(204, 102, 0));
        btVezes.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btVezes.setForeground(new java.awt.Color(255, 255, 255));
        btVezes.setText("×");
        btVezes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVezes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btVezes.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVezesActionPerformed(evt);
            }
        });

        btMenos.setBackground(new java.awt.Color(204, 102, 0));
        btMenos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btMenos.setForeground(new java.awt.Color(255, 255, 255));
        btMenos.setText("-");
        btMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMenos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btMenos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenosActionPerformed(evt);
            }
        });

        btTan.setBackground(new java.awt.Color(51, 153, 0));
        btTan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btTan.setForeground(new java.awt.Color(255, 255, 255));
        btTan.setText("tan");
        btTan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTanActionPerformed(evt);
            }
        });

        btTanh.setBackground(new java.awt.Color(51, 153, 0));
        btTanh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btTanh.setForeground(new java.awt.Color(255, 255, 255));
        btTanh.setText("tanh");
        btTanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTanh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTanhActionPerformed(evt);
            }
        });

        bt7.setBackground(new java.awt.Color(0, 0, 102));
        bt7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt7.setForeground(new java.awt.Color(255, 255, 255));
        bt7.setText("7");
        bt7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt8.setBackground(new java.awt.Color(0, 0, 102));
        bt8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt8.setForeground(new java.awt.Color(255, 255, 255));
        bt8.setText("8");
        bt8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt9.setBackground(new java.awt.Color(0, 0, 102));
        bt9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt9.setForeground(new java.awt.Color(255, 255, 255));
        bt9.setText("9");
        bt9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt9.setVerifyInputWhenFocusTarget(false);
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        btMais.setBackground(new java.awt.Color(204, 102, 0));
        btMais.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btMais.setForeground(new java.awt.Color(255, 255, 255));
        btMais.setText("+");
        btMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisActionPerformed(evt);
            }
        });

        btMaisOuMenos.setBackground(new java.awt.Color(153, 153, 0));
        btMaisOuMenos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btMaisOuMenos.setForeground(new java.awt.Color(255, 255, 255));
        btMaisOuMenos.setText("±");
        btMaisOuMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMaisOuMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisOuMenosActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(0, 0, 102));
        bt4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("4");
        bt4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(0, 0, 102));
        bt5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("5");
        bt5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(0, 0, 102));
        bt6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt6.setForeground(new java.awt.Color(255, 255, 255));
        bt6.setText("6");
        bt6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt1.setBackground(new java.awt.Color(0, 0, 102));
        bt1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("1");
        bt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(0, 0, 102));
        bt2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("2");
        bt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(0, 0, 102));
        bt3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("3");
        bt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        btIgual.setBackground(new java.awt.Color(0, 102, 102));
        btIgual.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btIgual.setForeground(new java.awt.Color(255, 255, 255));
        btIgual.setText("=");
        btIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btIgual.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });

        btRandom.setBackground(new java.awt.Color(153, 153, 0));
        btRandom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btRandom.setForeground(new java.awt.Color(255, 255, 255));
        btRandom.setText("Rand");
        btRandom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRandom.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRandomActionPerformed(evt);
            }
        });

        bt0.setBackground(new java.awt.Color(0, 0, 102));
        bt0.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bt0.setForeground(new java.awt.Color(255, 255, 255));
        bt0.setText("0");
        bt0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt0.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt0.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        btDecimal.setBackground(new java.awt.Color(0, 0, 102));
        btDecimal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btDecimal.setForeground(new java.awt.Color(255, 255, 255));
        btDecimal.setText(".");
        btDecimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDecimal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btDecimal.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecimalActionPerformed(evt);
            }
        });

        btMemMais.setBackground(new java.awt.Color(102, 153, 255));
        btMemMais.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btMemMais.setForeground(new java.awt.Color(255, 255, 255));
        btMemMais.setText("M+");
        btMemMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMemMais.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btMemMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemMaisActionPerformed(evt);
            }
        });
        btMemMais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btMemMaisKeyTyped(evt);
            }
        });

        btMemMenos.setBackground(new java.awt.Color(102, 153, 255));
        btMemMenos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btMemMenos.setForeground(new java.awt.Color(255, 255, 255));
        btMemMenos.setText("M-");
        btMemMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMemMenos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btMemMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemMenosActionPerformed(evt);
            }
        });
        btMemMenos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btMemMenosKeyTyped(evt);
            }
        });

        btMemoria.setBackground(new java.awt.Color(102, 153, 255));
        btMemoria.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btMemoria.setForeground(new java.awt.Color(255, 255, 255));
        btMemoria.setText("M");
        btMemoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMemoria.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemoriaActionPerformed(evt);
            }
        });
        btMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btMemoriaKeyTyped(evt);
            }
        });

        btMemSet.setBackground(new java.awt.Color(102, 153, 255));
        btMemSet.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btMemSet.setForeground(new java.awt.Color(255, 255, 255));
        btMemSet.setText("MS");
        btMemSet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMemSet.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btMemSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemSetActionPerformed(evt);
            }
        });
        btMemSet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btMemSetKeyTyped(evt);
            }
        });

        btMemClear.setBackground(new java.awt.Color(102, 153, 255));
        btMemClear.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btMemClear.setForeground(new java.awt.Color(255, 255, 255));
        btMemClear.setText("MC");
        btMemClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMemClear.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btMemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemClearActionPerformed(evt);
            }
        });
        btMemClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btMemClearKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btMemClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btMemSet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btMais, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btTan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btMaisOuMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btMemMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btMemMais, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btPi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btElevado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btLog, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btResto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btLn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btSen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSenh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btCos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(displayCalculadora))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(visor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btLn)
                        .addComponent(btE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btCosh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSenh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btElevado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFatorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btResto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btTanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMenos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVezes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMaisOuMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btMemMais, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btMemMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(bt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt0, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(btDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMemSet, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(btMemClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Eurostile", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculatron");
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(2560, 481));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        //Botão 6
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt6.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt6ActionPerformed

    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        String resposta;
        if (igual != false) {
            if (primeira == true) {
                segundoNumero = Double.parseDouble(displayCalculadora.getText());
            }
            switch (operacao) {
                case "+" -> {
                    if (primeira == true) {
                        result = (primeiroNumero + segundoNumero) * sinal;
                    } else {
                        result = (result + segundoNumero) * sinal;
                    }
                    if (result == (int) result) {
                        resposta = String.format("%.0f", result);
                    } else {
                        resposta = String.format("%.5f", result);
                    }
                    displayCalculadora.setText(resposta);
                }
                case "-" -> {
                    if (primeira == true) {
                        result = primeiroNumero - segundoNumero;
                    } else {
                        result = result - segundoNumero;
                    }
                    if (result == (int) result) {
                        resposta = String.format("%.0f", result);
                    } else {
                        resposta = String.format("%.5f", result);
                    }
                    displayCalculadora.setText(resposta);
                }
                case "*" -> {
                    if (primeira == true) {
                        result = (primeiroNumero * segundoNumero) * sinal;
                    } else {
                        result = (result * segundoNumero) * sinal;
                    }
                    if (result == (int) result) {
                        resposta = String.format("%.0f", result);
                    } else {
                        resposta = String.format("%.5f", result);
                    }
                    displayCalculadora.setText(resposta);
                }
                case "/" -> {
                    if (segundoNumero == 0 && !"!".equals(operacao)) {
                        displayCalculadora.setText("Não divida por 0 >:(");
                        if (i) {
                            oper = false;
                            displayCalculadora.setText("");
                            primeira = true;
                            igual = false;
                            result = 0;
                            primeiroNumero = 0;
                            segundoNumero = 0;
                            i = false;
                        }
                        i = true;
                    } else {
                        if (primeira == true) {
                            result = (primeiroNumero / segundoNumero) * sinal;
                        } else {
                            result = (result / segundoNumero) * sinal;
                        }
                        if (result == (int) result) {
                            resposta = String.format("%.0f", result);
                        } else {
                            resposta = String.format("%.5f", result);
                        }
                        displayCalculadora.setText(resposta);
                    }
                }
                case "%" -> {
                    if (!primeira) {
                        break;
                    }
                    result = (primeiroNumero % segundoNumero) * sinal;
                    resposta = String.format("%.0f", result);
                    displayCalculadora.setText(resposta);
                    break;
                }
                case "^" -> {
                    if (primeira == true) {
                        result = Math.pow(primeiroNumero, segundoNumero) * sinal;
                    } else {
                        result = Math.pow(result, segundoNumero) * sinal;
                    }
                    if (result == (int) result) {
                        resposta = String.format("%.0f", result);
                    } else {
                        resposta = String.format("%.5f", result);
                    }
                    displayCalculadora.setText(resposta);
                    break;
                }
                case "√" -> {
                    if (primeira == true) {
                        result = Math.pow(primeiroNumero, 1 / segundoNumero) * sinal;
                    } else {
                        result = Math.pow(result, 1 / segundoNumero) * sinal;
                    }
                    if (result == (int) result) {
                        resposta = String.format("%.0f", result);
                    } else {
                        resposta = String.format("%.5f", result);
                    }
                    displayCalculadora.setText(resposta);
                    break;
                }
                case "!" -> { //Quando não tem nenhum operador selecionado
                    break;
                }
                default -> {
                    break;
                }
            }
            primeira = false;
            if (burroMode) {
            double burrice = Double.parseDouble(displayCalculadora.getText()) + 1;
            if (result == (int) result) {
                displayCalculadora.setText(String.format("%.0f", burrice));
            } else {
                displayCalculadora.setText(String.format("%.5f", burrice));
            }
            }
            //visor.setText("");
        }
    }//GEN-LAST:event_btIgualActionPerformed

    private void btDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecimalActionPerformed
        //Botão Decimal
        String digitarNumero = displayCalculadora.getText() + btDecimal.getText();
        displayCalculadora.setText(digitarNumero);
    }//GEN-LAST:event_btDecimalActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        //Botão 1
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt1.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        //Botão 9
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt9.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        //Botão 2
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt2.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        //Botão 3
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt3.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        //Botão 4
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt4.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }

    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        //Botão 5
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt5.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        //Botão 7
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt7.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }

    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        //Botão 8
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt8.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt8ActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        oper = false;
        displayCalculadora.setText("");
        primeira = true;
        igual = false;
        result = 0;
        primeiroNumero = 0;
        segundoNumero = 0;
        i = false;
        visor.setText("");
        operacao = "!";
    }//GEN-LAST:event_btResetActionPerformed

    private void btMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenosActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
                displayCalculadora.setText("");
            }
            operacao = "-";
            visor.setText(operacao);
            //oper = false;
        }
        igual = false;
    }//GEN-LAST:event_btMenosActionPerformed

    private void btDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDividirActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
                displayCalculadora.setText("");
            }
            operacao = "/";
            visor.setText(operacao);
            //oper = false;
        }
        igual = false;
    }//GEN-LAST:event_btDividirActionPerformed

    private void btMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
                displayCalculadora.setText("");
            }
            operacao = "+";
            visor.setText(operacao);
            //oper = false;
        }
        igual = false;

    }//GEN-LAST:event_btMaisActionPerformed

    private void btVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVezesActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
                displayCalculadora.setText("");
            }
            operacao = "*";
            visor.setText(operacao);
            //oper = false;
        }
        igual = false;

    }//GEN-LAST:event_btVezesActionPerformed

    private void btMaisOuMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisOuMenosActionPerformed
        String resposta;
        if (oper) {
            double ops = Double.parseDouble(String.valueOf(displayCalculadora.getText()));
            ops = ops * (-1);
            result = result * (-1);
            if (ops == (int) ops || ops == -((int) ops)) {
                resposta = String.format("%.0f", ops);
            } else {
                resposta = String.format("%.5f", ops);
            }
            displayCalculadora.setText(resposta);
            operacao = "!";
            //oper = false;
        }
    }//GEN-LAST:event_btMaisOuMenosActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        //Botão 0
        if (!visor.getText().equals(btMemoria.getText())) {
            String digitarNumero = displayCalculadora.getText() + bt0.getText();
            displayCalculadora.setText(digitarNumero);
            oper = true;
            igual = true;
        }
    }//GEN-LAST:event_bt0ActionPerformed

    private void btRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRaizActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
                displayCalculadora.setText("");
            }
            operacao = "√";
            visor.setText(operacao);
            //oper = false;
        }
        igual = false;
    }//GEN-LAST:event_btRaizActionPerformed

    private void btElevadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElevadoActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
                displayCalculadora.setText("");
            }
            operacao = "^";
            visor.setText(operacao);
            //oper = false;
        }
        igual = false;
    }//GEN-LAST:event_btElevadoActionPerformed

    private void btRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestoActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
                displayCalculadora.setText("");
            }
            operacao = "%";
            visor.setText(operacao);
            //oper = false;
        }
        igual = false;

    }//GEN-LAST:event_btRestoActionPerformed

    private void btLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                result = Math.cos(primeiroNumero);
            } else {
                result = Math.cos(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btLog.getText());
        }
    }//GEN-LAST:event_btLogActionPerformed

    private void btTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTanActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                primeiroNumero = Math.toRadians(primeiroNumero);
                result = Math.tan(primeiroNumero);
            } else {
                result = Math.toRadians(result);
                result = Math.tan(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btTan.getText());
        }
    }//GEN-LAST:event_btTanActionPerformed

    private void btFatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFatorialActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (!(primeiroNumero != (int) primeiroNumero) || (primeiroNumero == 0)) {
                result = 1;
                for (int i = 2; i <= (int) primeiroNumero; i++) {
                    result = result * i;
                }
                if (result == (int) result) {
                    resposta = String.format("%.0f", result);
                } else {
                    resposta = String.format("%.5f", result);
                }
                displayCalculadora.setText(resposta);
            }
            visor.setText(btFatorial.getText());
        }
        igual = false;

    }//GEN-LAST:event_btFatorialActionPerformed

    private void btPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPiActionPerformed
        // Botão Pi
        //String digitarNumero = displayCalculadora.getText() + String.format("%.5f", Math.PI);
        displayCalculadora.setText(String.format("%.5f", Math.PI));
        oper = true;
        igual = true;
    }//GEN-LAST:event_btPiActionPerformed

    private void btCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCosActionPerformed
        // Botão Cosseno
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                primeiroNumero = Math.toRadians(primeiroNumero);
                result = Math.cos(primeiroNumero);
            } else {
                result = Math.toRadians(result);
                result = Math.cos(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btCos.getText());
        }
    }//GEN-LAST:event_btCosActionPerformed

    private void btSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSenActionPerformed
        // Botão Seno
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                primeiroNumero = Math.toRadians(primeiroNumero);
                result = Math.sin(primeiroNumero);
            } else {
                result = Math.toRadians(result);
                result = Math.sin(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btSen.getText());
        }
    }//GEN-LAST:event_btSenActionPerformed

    private void btEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEActionPerformed
        // Botão E
        //String digitarNumero = displayCalculadora.getText() + ;
        displayCalculadora.setText(String.format("%.5f", Math.E));
        oper = true;
        igual = true;
    }//GEN-LAST:event_btEActionPerformed

    private void btLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLnActionPerformed
        // Botão Ln        
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                result = Math.log(primeiroNumero);
            } else {
                result = Math.log(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btLn.getText());
        }
    }//GEN-LAST:event_btLnActionPerformed

    private void btRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRandomActionPerformed
        // Botão Random
        displayCalculadora.setText(String.format("%.5f", Math.random()));
        oper = true;
        igual = true;
    }//GEN-LAST:event_btRandomActionPerformed

    private void btResetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btResetKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btResetKeyTyped

    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed

    private void btSenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSenhActionPerformed
        // Botão Seno
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                primeiroNumero = Math.toRadians(primeiroNumero);
                result = Math.sinh(primeiroNumero);
            } else {
                result = Math.toRadians(result);
                result = Math.sinh(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btSenh.getText());
        }
    }//GEN-LAST:event_btSenhActionPerformed

    private void btTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTanhActionPerformed
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                primeiroNumero = Math.toRadians(primeiroNumero);
                result = Math.tanh(primeiroNumero);
            } else {
                result = Math.toRadians(result);
                result = Math.tanh(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btTanh.getText());
        }
    }//GEN-LAST:event_btTanhActionPerformed

    private void btCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCoshActionPerformed
        // Botão Cosseno
        if (oper) {
            primeira = true;
            igual = true;
            if (!"".equals(displayCalculadora.getText())) {
                primeiroNumero = Double.parseDouble(displayCalculadora.getText());
            }
            String resposta;
            if (primeira == true) {
                primeiroNumero = Math.toRadians(primeiroNumero);
                result = Math.cosh(primeiroNumero);
            } else {
                result = Math.toRadians(result);
                result = Math.cosh(result);
            }
            if (result == (int) result) {
                resposta = String.format("%.0f", result);
            } else {
                resposta = String.format("%.5f", result);
            }
            displayCalculadora.setText(resposta);
            visor.setText(btCosh.getText());
        }
    }//GEN-LAST:event_btCoshActionPerformed

    private void btMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemoriaActionPerformed
        displayCalculadora.setText(String.format("%.5f", mem));
        visor.setText(btMemoria.getText());
        oper = true;

    }//GEN-LAST:event_btMemoriaActionPerformed

    private void btMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btMemoriaKeyTyped

    }//GEN-LAST:event_btMemoriaKeyTyped

    private void btMemMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemMenosActionPerformed
        if (oper) {
            mem -= Double.parseDouble(displayCalculadora.getText());
            visor.setText(btMemMenos.getText());
            oper = true;
        }
    }//GEN-LAST:event_btMemMenosActionPerformed

    private void btMemMenosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btMemMenosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btMemMenosKeyTyped

    private void btMemMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemMaisActionPerformed
        if (oper) {
            mem += Double.parseDouble(displayCalculadora.getText());
            visor.setText(btMemMais.getText());
            oper = true;
        }
    }//GEN-LAST:event_btMemMaisActionPerformed

    private void btMemMaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btMemMaisKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btMemMaisKeyTyped

    private void btMemSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemSetActionPerformed
        if (oper) {
            mem = Double.parseDouble(displayCalculadora.getText());
            visor.setText(btMemSet.getText());
            oper = true;
        }
    }//GEN-LAST:event_btMemSetActionPerformed

    private void btMemSetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btMemSetKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btMemSetKeyTyped

    private void btMemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemClearActionPerformed
        if (oper) {
            mem = 0;

            if (visor.getText().equals(btMemoria.getText())) {
                displayCalculadora.setText(String.format("%.5f", mem));
                visor.setText(btMemoria.getText());
            }
            oper = true;
        }
    }//GEN-LAST:event_btMemClearActionPerformed

    private void btMemClearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btMemClearKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btMemClearKeyTyped

    private void btBurroModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBurroModeActionPerformed
        burroMode = !burroMode;
    }//GEN-LAST:event_btBurroModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btBurroMode;
    private javax.swing.JButton btCos;
    private javax.swing.JButton btCosh;
    private javax.swing.JButton btDecimal;
    private javax.swing.JButton btDividir;
    private javax.swing.JButton btE;
    private javax.swing.JButton btElevado;
    private javax.swing.JButton btFatorial;
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btLn;
    private javax.swing.JButton btLog;
    private javax.swing.JButton btMais;
    private javax.swing.JButton btMaisOuMenos;
    private javax.swing.JButton btMemClear;
    private javax.swing.JButton btMemMais;
    private javax.swing.JButton btMemMenos;
    private javax.swing.JButton btMemSet;
    private javax.swing.JButton btMemoria;
    private javax.swing.JButton btMenos;
    private javax.swing.JButton btPi;
    private javax.swing.JButton btRaiz;
    private javax.swing.JButton btRandom;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btResto;
    private javax.swing.JButton btSen;
    private javax.swing.JButton btSenh;
    private javax.swing.JButton btTan;
    private javax.swing.JButton btTanh;
    private javax.swing.JButton btVezes;
    private javax.swing.JTextField displayCalculadora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
